# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f09cc9769f3b1366ed76b7dead3997f935bb7abe5552ebe6ef79ed566505c9a97922cd5620530ab55ebfd5ad0ceec3908684f30373b28ecd46ae77eedd819090

test:
  secret_key_base: f9fc3428cafc501bec4df22a579188af0fab7edfa58c066bf92f291420853c64cbb0e59b60dd10cb7c2a544c8547f3ad0b6b31418a24b5b61e8ab3b4022ac96b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
